# Generated by Django 3.2.8 on 2021-11-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(default='', max_length=30)),
                ('eleve', models.CharField(default='', max_length=50)),
                ('id_age', models.IntegerField()),
                ('altitude', models.CharField(default='', max_length=30)),
                ('longitude', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
