# Generated by Django 3.2.8 on 2021-11-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mysql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('classe', models.CharField(max_length=70)),
                ('longitude', models.IntegerField()),
                ('altitude', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ecole',
        ),
    ]
